import type { Metadata } from 'next'
import '../globals.css'
import { fontQuestrial, fontUrbanist } from '@/utils/font'

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang='en'>
			<body className={`${fontUrbanist.variable} ${fontQuestrial.variable}`}>
				{children}
			</body>
		</html>
	)
}
