import type { Metadata } from 'next'
import '../globals.css'
import { fontQuestrial, fontUrbanist } from '@/utils/font'
import Navbar from '@/components/layouts/navbar/Navbar'

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang='en'>
			<body
				className={`w-full ${fontUrbanist.variable} ${fontQuestrial.variable} bg-[#F9F9F9]`}
			>
				<Navbar />
				{children}
			</body>
		</html>
	)
}
